### ISSUE TITLE
Cannot read property 'headers' of null in node_modules/wappalyzer/driver:66

### ISSUE THREAD

**Issue by francedema** [AliasIO/Wappalyzer#1748]
**My purpose** is read a file with 50 urls and, for every url,call wappalyzer code.

I installed wappalyzer following this [guide](https://www.npmjs.com/package/wappalyzer) with:

`npm i wappalyzer.`

The code is:

```
var fs = require('fs');
var async = require('async');
const file_url = "file_url_wappalyzer.txt";
//I call every wappalyzer function with 2000 ms of delay
const delay = 2000;

fs.readFile(file_url, 'utf8', function(err, data) {
	if (err) {
		return console.log(err);
	}
	var linee = data.split('\n');
	async.forEachOf(linee, function(linea, index, next) {
				linea = linea.trim();
				setTimeout(function() {
					async.waterfall([
						function(prossima) {
							if (linea && linea != "" && linea.length > 5) {					
								wappalyzer.analyze(linea)
									.then(json => {
										if (json && json.length > 0) {
											
										console.log(JSON.stringify(json, null, 2));
										return prossima();
                                                                              }
									})
									.catch(error => {
										//console.error(error);
										return prossima();

									});
							} else {
								return prossima();
							}
						}
					], function(err) {
						return next();

					});

				}, delay * (index + 1));
		},
		function(err) {
			if (err) {
				return console.log(err);
			}

		});
});
```
The code works for some urls but it gives me this exception:

```
TypeError: Cannot read property 'headers' of null
    at browser.visit.error (C:\Users\Eventi\AppData\Roaming\npm\node_modules\wap
palyzer\driver.js:66:56)
    at done (C:\Users\Eventi\AppData\Roaming\npm\node_modules\wappalyzer\node_mo
dules\zombie\lib\eventloop.js:589:11)
    at Timeout.timeout (C:\Users\Eventi\AppData\Roaming\npm\node_modules\wappaly
zer\node_modules\zombie\lib\eventloop.js:601:33)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```
And the code where exception is thrown is here:

```
browser.visit(url, error => {
        wappalyzer.driver.document = browser.document;
        //console.log("HEaders "+url);
        const headers = browser.resources['0'].response.headers;

        console.log(browser.document);
        const vars = Object.getOwnPropertyNames(browser.window);
        const html = browser.html();

        const hostname = wappalyzer.parseUrl(url).hostname;

        wappalyzer.analyze(hostname, url, {
          headers,
          html,
          env: vars
        });
      });
```
the url where wappalyzer throws error is always different, so I think is not a problem of url. Anyone can help me?

**Comment by AlexByte** [comment]
[Yes](https://github.com/AliasIO/Wappalyzer/issues/1624#issuecomment-327476319)

**Comment by francedema** [comment]
@AlexByte what am I wronging?

**Comment by AlexByte** [comment]
you need to change the module code.

**Comment by AlexByte** [comment]
Are you satisfied that wappalyzer npm does not define all technologies?
https://github.com/AliasIO/Wappalyzer/issues/1747

**Comment by AliasIO** [comment]
This should be fixed in the next update.
