### ISSUE TITLE
Run Wappalyzer inside AWS Lambda, exit problem

### ISSUE THREAD

**Issue by fones** [AliasIO/Wappalyzer#1817]
When I was running Wappalyzer inside Lambda funcion in AWS, I have always reach the Lambda timeout.

Problem is that Wappalyzer will not exit node process until you call `Process.exit([code])` by yourself.

But when I call it, after lambda callback, I get an rror:

```
2017-11-09T21:29:10.786Z	f6998ffe-c594-11e7-b53e-616df1cf90b0	{ Error: Timeout: did not get to load all resources on this page
    at Timeout.timeout (/var/task/node_modules/zombie/lib/eventloop.js:601:38)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
  cause: 
   Error: Timeout: did not get to load all resources on this page
       at Timeout.timeout (/var/task/node_modules/zombie/lib/eventloop.js:601:38)
       at ontimeout (timers.js:386:14)
       at tryOnTimeout (timers.js:250:5)
       at Timer.listOnTimeout (timers.js:214:5),
  isOperational: true }
```

How to "exit" Wappalyzer when getting callback from `wappalyzer.analyze()` ?

**Comment by AliasIO** [comment]
Are you using v5.1.5?

**Comment by fones** [comment]
Yes.

```
    "wappalyzer": {
      "version": "5.1.5",
      "resolved": "https://registry.npmjs.org/wappalyzer/-/wappalyzer-5.1.5.tgz",
      "integrity": "sha1-pw0vgIci5ZEX3LJUCAwJ15XPyVo=",
      "requires": {
        "request": "2.83.0",
        "zombie": "5.0.7"
      }
    },
```

**Comment by AliasIO** [comment]
And I'm assuming you're using `index.js` as the entrypoint? It will always call `process.exit()`:

https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/npm/index.js#L34

**Comment by fones** [comment]
My code below. It was not terminating the aws lambda, so I looked into `index.js` and find that there is an exit call. Is this exit neccessary to terminate? If so, it will not work in lambda env I think.

```
const options = {
  userAgent: 'Wappalyzer',
  maxWait: 3000
};

const wappalyzer = require('wappalyzer')(options);

exports.handler = function (event, context, callback) {

wappalyzer.analyze(event.domain)
      .then(wappResult => {
        callback(null, {
          wapp: wappResult,
        })
      })
      .catch(error => {
        console.error(error);
        callback(null, {
          wapp: null,
        })
      })
}
```

**Comment by AliasIO** [comment]
I would expect the callback to work actually.

How are you running Wappalyzer in Lambda? I'll try to reproduce it.

**Comment by fones** [comment]
The problem occurse even when I run this locally.

wapp.js file:
```
const options = {
  userAgent: 'Wappalyzer',
  maxWait: 3000
};

const wappalyzer = require('wappalyzer')(options);

wappalyzer.analyze('https://www.shoper.pl/')
  .then(wappResult => {
    console.log(wappResult)
  })
  .catch(error => {
    console.error(error);
  })
```

```
node wapp.js
```
Result is printed to console, but process want stop. You need to `Ctrl+C` to stop. It hangs. 

When I test on `github.com` it close nicely. Sometimes it close itself after minute or so after printing results.

**Comment by fones** [comment]
One more sample (on page: `http://www.ubrankootulanko.pl/`), after 5 minutes I hit Ctrl-C. So the callback is working but process is not terminated. In Lambda, this callback will not reach the caller.
```
time node wapp.js
[wappalyzer debug] [core] 4 apps detected: Google Analytics, Google Tag Manager, Modernizr, jQuery on http://www.ubrankootulanko.pl/
[ { name: 'Google Analytics',
    confidence: '100',
    version: 'UA',
    icon: 'Google Analytics.svg',
    website: 'http://google.com/analytics',
    categories: [ [Object] ] },
  { name: 'Google Tag Manager',
    confidence: '100',
    version: '',
    icon: 'Google Tag Manager.png',
    website: 'http://www.google.com/tagmanager',
    categories: [ [Object] ] },
  { name: 'Modernizr',
    confidence: '100',
    version: '',
    icon: 'Modernizr.png',
    website: 'http://www.modernizr.com',
    categories: [ [Object] ] },
  { name: 'jQuery',
    confidence: '100',
    version: '',
    icon: 'jQuery.svg',
    website: 'http://jquery.com',
    categories: [ [Object] ] } ]
^C
node wapp.js  3.77s user 0.41s system 1% cpu 5:18.01 total
```

**Comment by AliasIO** [comment]
Locally you'd have to call `process.exit()`. I expect Lambda to take care of that when you call the callback though.

**Comment by AliasIO** [comment]
You need to set [`context.callbackWaitsForEmptyEventLoop`](http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html#nodejs-prog-model-context-properties) to `false`. This works:

```javascript
const wappalyzer = require('wappalyzer')({});

exports.handler = (event, context, callback) => {
  context.callbackWaitsForEmptyEventLoop = false;

  wappalyzer.analyze('https://www.wappalyzer.com')
    .then(json => callback(null, json))
    .catch(callback);
};
```

**Comment by fones** [comment]
It works.
