### ISSUE TITLE
How to prevent browser.html() in npm driver from breaking everything?

### ISSUE THREAD

**Issue by avasilkov** [AliasIO/Wappalyzer#1837]
Is there a way to skip erroring elements or maybe analyze only text html if there is an error?
As i understand, here it broke on a single side script and halted.

`TypeError: str.replace is not a function
    at escapeString (/home//node_modules/parse5/lib/serialization/serializer.js:27:10)
    at module.exports.Serializer._serializeAttributes (/home//node_modules/parse5/lib/serialization/serializer.js:124:55)
    at module.exports.Serializer._serializeElement (/home//node_modules/parse5/lib/serialization/serializer.js:91:10)
    at module.exports.Serializer._serializeChildNodes (/home//node_modules/parse5/lib/serialization/serializer.js:72:22)
    at module.exports.Serializer._serializeElement (/home//node_modules/parse5/lib/serialization/serializer.js:114:14)
    at module.exports.Serializer._serializeChildNodes (/home//node_modules/parse5/lib/serialization/serializer.js:72:22)
    at module.exports.Serializer._serializeElement (/home//node_modules/parse5/lib/serialization/serializer.js:114:14)
    at module.exports.Serializer._serializeChildNodes (/home//node_modules/parse5/lib/serialization/serializer.js:72:22)
    at module.exports.Serializer.serialize (/home//node_modules/parse5/lib/serialization/serializer.js:57:10)
    at exports.domToHtml (/home//node_modules/jsdom/lib/jsdom/browser/domtohtml.js:14:25)
    at core.(anonymous function).get outerHTML (/home//node_modules/jsdom/lib/jsdom/level1/core.js:676:12)
    at core.(anonymous function).get outerHTML [as outerHTML] (https://www.ranker.com/i10c@p1/client/nv-8.2.75/abd/instart.js:2:47867)
    at /home//node_modules/zombie/lib/index.js:566:21
    at Array.map (<anonymous>)
    at Browser.html (/home//node_modules/zombie/lib/index.js:565:82)
    at browser.wait.catch.finally (/home//trackr-wappa/src/drivers/npm/driver.js:96:34)`

**Comment by AliasIO** [comment]
Error handling should be improved in the next version. Do you have a test case for this?

**Comment by avasilkov** [comment]
I do.
node index.js https://www.ranker.com --userAgent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'
Useragent is important gere for some reason.
Also this one as well
node index.js http://adapcon.com.br
and this one
node index.js http://agivis.com.br
etc. From what I understand, it breaks on completing some invalid third party javascript and it causes entire wappalyzer to break even if this script was doing something minimal and wasn't eve contributing to the results. It's obviosly a zombie issue, will we be able to prevent wappalyzer from crashing because of these errors?

**Comment by AliasIO** [comment]
Fixed in 0c53f79a547159b69d6f1f7d5e6137f7a45535ed.
