### ISSUE TITLE
console errors

### ISSUE THREAD

**Issue by landsman** [AliasIO/Wappalyzer#1881]
Hi, 
I can see some errors in console, on all pages:

```
VM6370 extensions::messaging:102 Uncaught Error: Attempting to use a disconnected port object
    at PortImpl.postMessage (extensions::messaging:102:13)
    at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:138:26)
    at chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:68:53755
    at chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:68:51571
    at r (chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:68:51229)

VM6370 extensions::messaging:102 Uncaught Error: Attempting to use a disconnected port object
    at PortImpl.postMessage (extensions::messaging:102:13)
    at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:138:26)
    at chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:68:53755
    at chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:68:51571
    at r (chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:68:51229)
```

My browser: `Version 62.0.3202.94 (Official Build) (64-bit)`, OS: `macOS Hight Sierra 10.13.1`
Can you check it please?

**Comment by gadcam** [comment]
Hi,
Did you try to disable Wappalyzer to check if it was the culprit ?

**Comment by landsman** [comment]
hey, you right
