### ISSUE TITLE
Last version is broken

### ISSUE THREAD

**Issue by fedekau** [AliasIO/Wappalyzer#1915]
When running `wappalyzer 5.2.1` I get the following error

```
Error: Cannot find module './wappalyzer'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/user/folder1/node_modules/wappalyzer/driver.js:3:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Looking at `node_modules/wappalyzer` there is no `wappalyzer.js` file but it is being required from the `driver.js` file.

**Comment by kovaroman** [comment]
The same problem... `wappalyzer.js` is missing from NPM package for the las version...

**Comment by AliasIO** [comment]
Wow, that's a bit of an oversight on my part. Sorry about that. I pushed v5.2.2.

**Comment by jvoisin** [comment]
Shall we add a travis job that is building and checking packages?

**Comment by AliasIO** [comment]
Solid plan.

**Comment by JR0ch17** [comment]
@AliasIO , I'm getting a similar behavior again today for version 5.8.4.

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'wappalyzer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/recon-jr0ch17/src/wappalyzer2.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Any idea what's up?
