### ISSUE TITLE
Cannot read property 'getElementsByTagName' of null

### ISSUE THREAD

**Issue by hbakhtiyor** [AliasIO/Wappalyzer#1931]
when analyzing some websites, gotting the error, e.g. 194.79.56.215

```
 TypeError: Cannot read property 'getElementsByTagName' of null
     at browser.wait.catch.finally (/demo/node_modules/wappalyzer/driver.js:157:44)
     at PassThroughHandlerContext.finallyHandler (/demo/node_modules/bluebird/js/release/finally.js:56:23)
     at PassThroughHandlerContext.tryCatcher (/demo/node_modules/bluebird/js/release/util.js:16:23)
     at Promise._settlePromiseFromHandler (/demo/node_modules/bluebird/js/release/promise.js:512:31)
     at Promise._settlePromise (/demo/node_modules/bluebird/js/release/promise.js:569:18)
     at Promise._settlePromise0 (/demo/node_modules/bluebird/js/release/promise.js:614:10)
     at Promise._settlePromises (/demo/node_modules/bluebird/js/release/promise.js:693:18)
     at Promise._fulfill (/demo/node_modules/bluebird/js/release/promise.js:638:18)
     at Promise._settlePromise (/demo/node_modules/bluebird/js/release/promise.js:582:21)
     at Promise._settlePromise0 (/demo/node_modules/bluebird/js/release/promise.js:614:10)
     at Promise._settlePromises (/demo/node_modules/bluebird/js/release/promise.js:693:18)
     at Promise._fulfill (/demo/node_modules/bluebird/js/release/promise.js:638:18)
     at /demo/node_modules/bluebird/js/release/nodeback.js:42:21
     at EventLoop.done (/demo/node_modules/zombie/lib/eventloop.js:589:11)
     at Object.onceWrapper (events.js:313:30)
     at emitNone (events.js:111:20)
```

**Comment by AliasIO** [comment]
Thanks, this is fixed in v5.4.2.
