### ISSUE TITLE
Null Exceptions is not handled properly 

### ISSUE THREAD

**Issue by MrKira** [AliasIO/Wappalyzer#1961]
this is my log show's that the null exceptions is not handled properly in wappalayzer driver.js

```
[wappalyzer debug] [driver] depth: 1; delay: 0ms; url: http://www.taxi-benoot.be/
[wappalyzer debug] [core] 1 apps detected: Apache on http://www.taxi-benoot.be/
Unhandled rejection TypeError: Cannot read property 'getElementsByTagName' of null
    at browser.wait.catch.finally.e (/opt/wappalyzer/driver.js:138:43)
    at PassThroughHandlerContext.finallyHandler (/opt/wappalyzer/node_modules/bluebird/js/release/finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (/opt/wappalyzer/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/wappalyzer/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/wappalyzer/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/wappalyzer/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/wappalyzer/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/opt/wappalyzer/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (/opt/wappalyzer/node_modules/bluebird/js/release/promise.js:582:21)
    at Promise._settlePromise0 (/opt/wappalyzer/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/wappalyzer/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/opt/wappalyzer/node_modules/bluebird/js/release/promise.js:638:18)
    at /opt/wappalyzer/node_modules/bluebird/js/release/nodeback.js:42:21
    at EventLoop.done (/opt/wappalyzer/node_modules/zombie/lib/eventloop.js:589:11)
    at EventLoop.g (events.js:292:16)
    at emitNone (events.js:91:20)
```

**Comment by AliasIO** [comment]
This has been fixed too.
