### ISSUE TITLE
Unhandled rejection TypeError: Cannot use 'in' operator to search for 'nextElementSibling' in null

### ISSUE THREAD

**Issue by MrKira** [AliasIO/Wappalyzer#1965]
```
Unhandled rejection TypeError: Cannot use 'in' operator to search for 'nextElementSibling' in null
    at /Users/username/Projects/wappalayzer-test/node_modules/nwmatcher/src/nwmatcher-noqsa.js:133:26
    at addNwmatcher (/Users/username/Projects/wappalayzer-test/node_modules/jsdom/lib/jsdom/living/selectors.js:66:27)
    at HTMLDocument.<anonymous> (/Users/username/Projects/wappalayzer-test/node_modules/jsdom/lib/jsdom/living/selectors.js:23:23)
    at HTMLDocument.querySelectorAll (/Users/username/Projects/wappalayzer-test/node_modules/jsdom/lib/jsdom/utils.js:176:45)
    at Object.query (/Users/username/Projects/wappalayzer-test/node_modules/zombie/lib/dom/jsdom_patches.js:20:18)
    at updateHTMLCollection (/Users/username/Projects/wappalayzer-test/node_modules/jsdom/lib/jsdom/living/html-collection.js:39:58)
    at new HTMLCollection (/Users/username/Projects/wappalayzer-test/node_modules/jsdom/lib/jsdom/living/html-collection.js:14:5)
    at module.exports.create (/Users/username/Projects/wappalayzer-test/node_modules/jsdom/lib/jsdom/living/html-collection.js:92:10)
    at HTMLDocument.scripts (/Users/username/Projects/wappalayzer-test/node_modules/zombie/lib/dom/jsdom_patches.js:19:10)
    at browser.wait.catch.finally (/Users/username/Projects/wappalayzer-test/node_modules/wappalyzer/driver.js:146:43)
    at PassThroughHandlerContext.finallyHandler (/Users/username/Projects/wappalayzer-test/node_modules/bluebird/js/release/finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (/Users/username/Projects/wappalayzer-test/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/username/Projects/wappalayzer-test/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/username/Projects/wappalayzer-test/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/username/Projects/wappalayzer-test/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/username/Projects/wappalayzer-test/node_modules/bluebird/js/release/promise.js:693:18)
```

**Comment by AliasIO** [comment]
Thanks, fixed in v5.4.1.
