### ISSUE TITLE
[BUG] Wappalyzer unhandled exception

### ISSUE THREAD

**Issue by dege88** [AliasIO/Wappalyzer#2167]
When analyzing this url from wappalyzer an unhandled exception get thrown by Zombie:
`http://www.pool.co.il/product/%D7%A2%D7%A8%D7%9B%D7%AA-%D7%94%D7%9B%D7%9C-%D7%9B%D7%9C%D7%95%D7%9C-%D7%A7%D7%9C%D7%90%D7%A1%D7%99%D7%A7-%D7%91%D7%A8%D7%99%D7%9B%D7%AA-intex-%D7%90%D7%9
5%D7%9C%D7%98%D7%A8%D7%94-%D7%90%D7%95%D7%91%D7%9C%D7%99%D7%AA-107305549-%D7%93%D7%92%D7%9D-%D7%9E%D7%A9%D7%95%D7%A4%D7%A8-2017-28192`

error:
```
/node_modules/zombie/lib/fetch.js:496
      if (responseInit.status < 200 || responseInit.status > 599) throw new RangeError('Status code ' + responseInit.status + ' not in range');
                                                                  ^

RangeError: Status code 999 not in range
    at new Response (/node_modules/zombie/lib/fetch.js:496:73)
    at Request.<anonymous> (/node_modules/zombie/lib/pipeline.js:330:21)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (/node_modules/request/request.js:1068:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```
on the latest version of Wappalyzer used as a node module on linux

The error is thrown by Zombie but the exception is unhandled and this terminate the whole node process

**Comment by AliasIO** [comment]
Thanks, I added a workaround in 916b3af5c030b159020a73857931d6a7f5e39d64. Looks like the issue has already been raised with Zombie.js.

https://github.com/assaf/zombie/issues/1135
