### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by superhac** [AliasIO/Wappalyzer#2270]
When trying to run the first time I'm getting the following error:

```
 $ node node_modules/wappalyzer/index.js https://www.test.com
/home/tommy/node_modules/wappalyzer/driver.js:292
  crawl(pageUrl, index = 1, depth = 1) {
                       ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/tommy/node_modules/wappalyzer/index.js:3:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

Any Idea what the issue is?

**Comment by superhac** [comment]
You can close this.  I just noticed I was running 4.2.X version of nodejs.   Upgraded to 8.x and we're good.
