### ISSUE TITLE
Cannot read property '_addFeature' of undefined

### ISSUE THREAD

**Issue by hbakhtiyor** [AliasIO/Wappalyzer#2333]
when analyzing some websites, gotting the error, e.g. wingtsun dot hr

```
at new HTMLDocument (/demo/node_modules/jsdom/lib/jsdom/level2/html.js:211:23)
at new Window (/demo/node_modules/jsdom/lib/jsdom/browser/Window.js:53:20)
at createDocument (/demo/node_modules/zombie/lib/document.js:558:16)
at loadDocument (/demo/node_modules/zombie/lib/document.js:857:18)
at History.open (/demo/node_modules/zombie/lib/history.js:267:22)
at Tabs.open (/demo/node_modules/zombie/lib/tabs.js:92:20)
at Browser.visit (/demo/node_modules/zombie/lib/index.js:620:17)
at Driver.visit (/demo/node_modules/wappalyzer/driver.js:124:13)
at sleep.then (/demo/node_modules/wappalyzer/driver.js:111:90)

```

**Comment by ScionOfBytes** [comment]
@hbakhtiyor Consistent across browsers and versions?

**Comment by hbakhtiyor** [comment]
the bug for npm node module

**Comment by AliasIO** [comment]
Can you give an example of a website this happens on? Isn't it just an error on the web page?

**Comment by hbakhtiyor** [comment]
just simple code

```js
  const options = {
    debug: false,
    delay: 500,
    maxDepth: 3,
    maxUrls: 10,
    maxWait: 1000,
    recursive: true,
    requestTimeout: 3000,
    userAgent: 'some useragent',
  };

  try {
    const wappalyzer = new Wappalyzer(url, options);
    const result = await wappalyzer.analyze();
  } catch (err) {
    console.error('Error while analyzing technologies of the website', {err, url});
  }

```

**Comment by kyletaylored** [comment]
Can't reproduce, this seems to work fine on the latest version.

```js
const Wappalyzer = require('wappalyzer');
const url = "http://www.wingtsun.hr";
const options = {
    debug: false,
    delay: 500,
    maxDepth: 3,
    maxUrls: 10,
    maxWait: 1000,
    recursive: true,
    requestTimeout: 3000,
    userAgent: 'some useragent',
  };

  const wappalyzer = new Wappalyzer(url, options);
  wappalyzer.analyze()
  .then(json => {
      console.log(json);
  })
  .catch(error => {
    console.log(error);
});
```
