### ISSUE TITLE
TypeError: Cannot destructure property `scripts` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by mramsundar** [AliasIO/Wappalyzer#2564]
Simple NodeJS app.

const Wappalyzer = require ('wappalyzer/wappalyzer');
console.log(require ('wappalyzer/wappalyzer'));

const options = {
  debug: true,
  delay: 0,
  maxDepth: 0,
  maxUrls: 10,
  maxWait: 5000,
  recursive: true,
  htmlMaxCols: Number.MAX_SAFE_INTEGER,
  htmlMaxRows: Number.MAX_SAFE_INTEGER,
  userAgent: 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36'
};

const wappalyzer = new Wappalyzer('http://runifico.com/', options);

wappalyzer.analyze().then(console.log);

This is the error I get - 

TypeError: Cannot destructure property `scripts` of 'undefined' or 'null'.
    at Wappalyzer.analyze (C:\code\CustomAppsProfile\node_modules\wappalyzer\wappalyzer.js:155:9)
    at Object.<anonymous> (C:\code\CustomAppsProfile\index.js:18:12)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)

Any idea on how to solve this?

**Comment by AliasIO** [comment]
It might be because `maxDepth` is set to `0`.
