### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by aliahmad490** [AliasIO/Wappalyzer#2694]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
Bug
**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
NPM driver
**What is the current behavior ?**
A type error is thrown when running analyze on "https://www.datwyler.com/en/home/".
**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
```
const Wappalyzer = require('wappalyzer');

const wappalyzer = new Wappalyzer('https://www.datwyler.com/en/home/', {
  debug: false,
  delay: 1,
  maxDepth: 3,
  maxUrls: 10,
  maxWait: 5000,
  recursive: true,
  userAgent: 'Wappalyzer',
  htmlMaxCols: 2000,
  htmlMaxRows: 2000,
});

wappalyzer.analyze()
  .then(response => {
    console.log(`Response received from wappalyzer:`, response);
  })
  .catch(error => {
    console.error('An error occurred in Wappalyzer:', error);
  }); 

```
This produces the following output:
```
(node:1342) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of undefined
    at Array.reduce.call (/node_modules/wappalyzer/driver.js:245:27)
    at Array.reduce (<anonymous>)
    at Driver.visit (/node_modules/wappalyzer/driver.js:242:49)
(node:1342) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1342) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1342) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of undefined
    at Array.reduce.call (/node_modules/wappalyzer/driver.js:245:27)
    at Array.reduce (<anonymous>)
    at Driver.visit (/node_modules/wappalyzer/driver.js:242:49)
(node:1342) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```
**What is the expected behavior ?**
Wappalyzer should not throw an error.
**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
Wappalyzer version 5.8.2.

**Comment by kyletaylored** [comment]
I found the issue. In this particular site, it's picking up invalid links, which is tripping up the link parser. The fix is likely to catch these broken links before they're attempted to be matched. In this specific instance, it's detecting SVGs.

```
[wappalyzer debug] [driver] Skipping; element: [object SVGElement]; message: Not a valid link.
```

**Comment by kyletaylored** [comment]
Added a check to verify that the link coming through is actually a link (proves a `protocol` property).
