### ISSUE TITLE
'utf-8' codec can't decode byte 0xba in position xxx

### ISSUE THREAD

**Issue by xhf79** [AliasIO/Wappalyzer#2746]
The website: http://www.vodxc.com

When I use builtwith.parse parse it, I meet the Error:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 248: invalid start byte.

Code:
>>> import builtwith
>>> builtwith.parse('http://www.vodxc.com')
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    builtwith.parse('http://www.vodxc.com')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\builtwith\__init__.py", line 66, in builtwith
    if contains(html, snippet):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\builtwith\__init__.py", line 111, in contains
    v = v.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 248: invalid start byte

**Comment by kyletaylored** [comment]
That's BuiltWith, which is a competing technology to Wappalyzer.

Wappalyzer doesn't have a Python module, so you'll want to file this on their [Bitbucket repository](https://bitbucket.org/richardpenman/builtwith).
