### ISSUE TITLE
Error when I try to Run wappalyzer  

### ISSUE THREAD

**Issue by doflamingo-lab** [AliasIO/wappalyzer#3039]
Hello 
This the Error Content : 

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './build/Release/cld'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/wappalyzer/node_modules/cld/index.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by AliasIO** [comment]
Are you running from source or the NPM module? Did you run `npm install`?

**Comment by doflamingo-lab** [comment]
Yes i use npm install

**Comment by Tropicalista** [comment]
Same error here. I installed globally using:

`npm i -g wappalyzer`

**Comment by Tropicalista** [comment]
With the latest build, my problem gone away. Thanks
