### ISSUE TITLE
command error

### ISSUE THREAD

**Issue by TroyBarlow** [AliasIO/wappalyzer#3369]
![image](https://user-images.githubusercontent.com/15190314/94106539-2d69fd80-fe6e-11ea-8a28-fc1db2fc0055.png)

**Comment by TroyBarlow** [comment]
升级nodejs 并重新yarn install   yarn run link 后，问题解决

**Comment by AliasIO** [comment]
Are you using the latest version? I'm seeing a different error. The URL needs to start with `http://` or `https://`.

```
$ node cli.js www.baidu.com
Error: TypeError [ERR_INVALID_URL]: Invalid URL: www.baidu.com
    at new Site (/Users/elbert/Sites/wappalyzer/extension/src/drivers/npm/driver.js:192:13)
    at Driver.open (/Users/elbert/Sites/wappalyzer/extension/src/drivers/npm/driver.js:163:12)
    at /Users/elbert/Sites/wappalyzer/extension/src/drivers/npm/cli.js:85:35
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by kyletaylored** [comment]
URL requires formatting using `http` or `https`.
