### ISSUE TITLE
wappazyler on raspbian

### ISSUE THREAD

**Issue by vay3t** [AliasIO/wappalyzer#3423]
**Platform**
* NPM

**Describe the bug**
i cant run wappalyzer on Raspbian. i have this bug: 

```
Error: Error: Failed to launch the browser process!
/usr/local/share/.config/yarn/global/node_modules/puppeteer/.local-chromium/linux-800071/chrome-linux/chrome: 26: /usr/local/share/.config/yarn/global/node_modules/puppeteer/.local-chromium/linux-800071/chrome-linux/chrome: Syntax error: Unterminated quoted string


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at Driver.init (/usr/local/share/.config/yarn/global/node_modules/wappalyzer/driver.js:172:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /usr/local/share/.config/yarn/global/node_modules/wappalyzer/cli.js:83:5
```

**To Reproduce**
1. `sudo yarn global add wappazyler`
2. `wappalyzer https://google.com`

**Expected behavior**
run wappalyzer

**Additional context**
the binaries of chrome were compiled in x64

**Comment by AliasIO** [comment]
That sounds like a Puppeteer issue. You can try enabling debug output with `wappalyzer https://google.com -d` but I'm not sure if that will help you much.

**Comment by vay3t** [comment]
output:

```
wappalyzer | log | driver | Launching browser...
Error: Error: Failed to launch the browser process!
/usr/local/share/.config/yarn/global/node_modules/puppeteer/.local-chromium/linux-800071/chrome-linux/chrome: 26: /usr/local/share/.config/yarn/global/node_modules/puppeteer/.local-chromium/linux-800071/chrome-linux/chrome: Syntax error: Unterminated quoted string


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at Driver.init (/usr/local/share/.config/yarn/global/node_modules/wappalyzer/driver.js:172:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /usr/local/share/.config/yarn/global/node_modules/wappalyzer/cli.js:83:5
```

**Comment by vay3t** [comment]
i like change the default browser used in puppeteer when i use wappalyzer

**Comment by AliasIO** [comment]
So the error is `Syntax error: Unterminated quoted string`. I'm not sure where that's coming from but it doesn't seem to be a Wappalyzer issue.

**Comment by tranduyhung** [comment]
I know this is an old issue but I had the same problem on Docker, to fix it I needed to install Chrome, thanks to [Alex](https://dev.to/cloudx/how-to-use-puppeteer-inside-a-docker-container-568c). Here is a part of my Docker file

```
FROM node:slim AS app

# We don't need the standalone Chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

# Install Google Chrome Stable and fonts
# Note: this installs the necessary libs to make the browser work with Puppeteer.
RUN apt-get update && apt-get install curl gnupg -y \
  && curl --location --silent https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update \
  && apt-get install google-chrome-stable -y --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*
```

I am not familiar with Raspbian but maybe we need to install Chrome as well.
