### ISSUE TITLE
Latest  6.5.26 version broken - outdated 6.5.25 in NPM

### ISSUE THREAD

**Issue by afoustbf** [AliasIO/wappalyzer#3760]
When running the latest `wappalyzer 6.5.26` I get the following:

```
node src/drivers/npm/cli.js https://example.com
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module './wappalyzer'
Require stack:
- /root/tools/wappalyzer/src/drivers/npm/driver.js
- /root/tools/wappalyzer/src/drivers/npm/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/tools/wappalyzer/src/drivers/npm/driver.js:7:20)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/tools/wappalyzer/src/drivers/npm/driver.js',
    '/root/tools/wappalyzer/src/drivers/npm/cli.js'
  ]
}
```

When investigating I ran into #1915 and looked at https://www.npmjs.com/search?q=wappalyzer
As you can see below, latest nppm version is 6.5.25 and looks like it isn't getting pulled, hence why we can't find ./wappalyzer
![image](https://user-images.githubusercontent.com/69817281/107231784-ef651480-69dd-11eb-9168-42cb934d9092.png)

Thanks!

**Comment by AliasIO** [comment]
You won't have this issue if you're using the `wappalyzer` NPM package rather than running from source but v6.5.26 has now been published.
