### ISSUE TITLE
SyntaxError: Invalid regular expression

### ISSUE THREAD

**Issue by Kikobeats** [AliasIO/wappalyzer#3932]
Looks like the rule files contains an invalid regex:

```bash
SyntaxError: Invalid regular expression: /[data-ackee-domain-id], [data-ackee-server]/: Range out of order in character class
    at new RegExp (<anonymous>)
    at /home/node/app/node_modules/wappalyzer-core/wappalyzer.js:372:27
    at Array.reduce (<anonymous>)
    at Object.parsePattern (/home/node/app/node_modules/wappalyzer-core/wappalyzer.js:360:10)
    at /home/node/app/node_modules/wappalyzer-core/wappalyzer.js:336:37
    at Array.map (<anonymous>)
    at /home/node/app/node_modules/wappalyzer-core/wappalyzer.js:336:9
    at Array.reduce (<anonymous>)
    at transformPatterns (/home/node/app/node_modules/wappalyzer-core/wappalyzer.js:333:42)
    at /home/node/app/node_modules/wappalyzer-core/wappalyzer.js:273:14
```

**Comment by AliasIO** [comment]
This was fixed, thanks.
