### ISSUE TITLE
Wappalyzer CLI not working

### ISSUE THREAD

**Issue by tester000One** [AliasIO/wappalyzer#5493]
**Platform**
Which platform does the bug apply to?
* NPM
* Wappalyzer CLI

**Describe the bug**

Getting Syntax Error on running npm module or the wappalyzer CLI

/redacted/redacted/Projects/Temp/node_modules/wappalyzer/driver.js:986
        status: this.analyzedUrls[url.href]?.status || 0,
                                            ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/k4k4r07/Projects/Temp/wappalyzer.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**To Reproduce**
1. Install npm i -g wappalyzer and use wappalyzer -h or npm i wappalyzer then create use.js with code on https://www.npmjs.com/package/wappalyzer and using node use.js or clone the github repo and yarn install and yarn run link, and then on running node src/drivers/npm/cli.js https://example.com all of these give the above error

**Comment by robsongajunior** [comment]
Probably  you dont configure the driver
https://github.com/AliasIO/wappalyzer#chrome-extension

**Comment by AliasIO** [comment]
Please upgrade to Node 14 or higher.

**Comment by tester000One** [comment]
Hi @AliasIO Thanks for answering, updaing th node worked
