### ISSUE TITLE
SyntaxError in src/drivers/npm/driver.js

### ISSUE THREAD

**Issue by 0x4bit** [AliasIO/wappalyzer#5684]
**Platform**
Which platform does the bug apply to?
* NPM

**Describe the bug**
In /src/drivers/npm/driver.js is a SyntaxError causing typo.
Line 993 reads:
`status: this.analyzedUrls[url.href]?.status || 0,`
The questionmark after `[url.href] causes this error upon execution:
```
/opt/wappalyzer/src/drivers/npm/driver.js:993
        status: this.analyzedUrls[url.href]?.status || 0,
                                            ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/wappalyzer/src/drivers/npm/cli.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```
Removal of the questionmark leads to a running program without errors.

**To Reproduce**
1. git clone https://github.com/aliasio/wappalyzer && cd wappalyzer
2. yarn install
3. yarn run link
4. node /opt/wappalyzer/src/drivers/npm/cli.js

**Expected behavior**
The program runs without error.

**Additional context**
Sorry I'm at work. Would've created a pull request if being at home.

**Comment by AliasIO** [comment]
You need to upgrade to Node 14 or higher.
