### ISSUE TITLE
The widget module is deprecated

### ISSUE THREAD

**Issue by Ranger2000** [AliasIO/Wappalyzer#697]
Wappalyzer 3.0.13 produce an error in the Browser console in Firefox 32.0.
Solution is to discontinue using that require('widget') and move to require('sdk/ui')
See: https://blog.mozilla.org/addons/2014/03/13/new-add-on-sdk-australis-ui-features-in-firefox-29/

"DEPRECATED: The widget module is deprecated.  Please consider using the sdk/ui module instead.
Traceback (most recent call last):
  File "resource://services-sync/status.js", line 36, in this.Status._authManager
    cb.wait();
  File "resource://services-common/async.js", line 145, in makeSpinningCallback/callback.wait
    callback.wait = function() Async.waitForSyncCallback(cb);
  File "resource://services-common/async.js", line 102, in waitForSyncCallback
    thread.processNextEvent(true);
  File "resource://gre/modules/Promise-backend.js", line 745, in this.PromiseWalker.walkerLoop
    this.handlers.shift().process();
  File "resource://gre/modules/Promise-backend.js", line 866, in Handler.prototype.process
    nextValue = this.onResolve.call(undefined, nextValue);
  File "resource://gre/modules/commonjs/sdk/addon/runner.js", line 115, in startup/<
    run(options);
  File "resource://gre/modules/commonjs/sdk/addon/runner.js", line 179, in run
    program.main({
  File "resource://wappalyzer-at-crunchlabz-dot-com/wappalyzer/lib/driver.js", line 20, in exports.main
    w.init();
  File "resource://wappalyzer-at-crunchlabz-dot-com/wappalyzer/lib/wappalyzer.js", line 236, in w.init
    driver('init');
  File "resource://wappalyzer-at-crunchlabz-dot-com/wappalyzer/lib/wappalyzer.js", line 146, in driver
    return w.driver[func](args);
  File "resource://wappalyzer-at-crunchlabz-dot-com/wappalyzer/lib/driver.js", line 366, in w.driver.init
    windows.push(new Window(win));
  File "resource://wappalyzer-at-crunchlabz-dot-com/wappalyzer/lib/driver.js", line 48, in Window
    this.widget = widget || ( widget = new Widget() );
  File "resource://wappalyzer-at-crunchlabz-dot-com/wappalyzer/lib/driver.js", line 218, in Widget
    this.widget = require('sdk/widget').Widget({
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 633, in require
    freeze(load(loader, module));
  File "resource://gre/modules/commonjs/sdk/loader/cuddlefish.js", line 129, in CuddlefishLoader/options<.load
    result = load(loader, module);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 313, in load
    evaluate(sandbox, module.uri);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 262, in evaluate
    : loadSubScript(uri, sandbox, encoding);
  File "resource://gre/modules/commonjs/sdk/widget.js", line 59, in null
    require("./util/deprecate").deprecateUsage(
  File "resource://gre/modules/commonjs/sdk/util/deprecate.js", line 18, in deprecateUsage
    let stack = get().slice(2);"

**Comment by AliasIO** [comment]
Wappalyzer is no longer using the widget module.
