### ISSUE TITLE
Icon test fails in Docker

### ISSUE THREAD

**Issue by DaAwesomeP** [AliasIO/Wappalyzer#811]
The icon test fails due to missing its dependencies. NPM is installing them to `/home/wappalyzer/node`, but the script is running out of `bin/`. Only CLI NPM libraries (like jsonlint) can be added to the PATH and work. NPM needs to install the dependencies to `bin/` or its direct parent. This is why the Travis test works and the Docker/Vagrant one doesn't.

**Comment by AliasIO** [comment]
It's working for me in Docker and Travis. Try rebuilding with `vagrant destroy -y && vagrant up`. The `$WAPPALYZER_NODE_PATH` environment variable needs to be set.

**Comment by DaAwesomeP** [comment]
I destroyed/re-created the vagrant as well as updating my git and I still have the problem:
```bash
Validating apps.json...
Validating regular expressions...
Validating icons...

module.js:340
    throw err;
          ^
Error: Cannot find module 'file-type'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/wappalyzer/synced/bin/wappalyzer-validate-icons:7:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by AliasIO** [comment]
I'm pushing my latest Docker image now, either build locally or try it in 10 minutes.

--
