### ISSUE TITLE
Fresh install of docker + vagrant, get typeError

### ISSUE THREAD

**Issue by fxfactorial** [AliasIO/Wappalyzer#896]
I'm on Debian Jessie and just freshly installed Docker.io (That's how docker is called in debian's apt-get) and vagrant. Note I have to use sudo, otherwise I get this error:

```shell
vagrant up
Bringing machine 'default' up with 'docker' provider...
A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: ["docker", "ps", "-a", "-q", "--no-trunc", {:notify=>[:stdout, :stderr]}]

Stderr: time="2015-06-24T15:45:19-07:00" level=fatal msg="Get http:///var/run/docker.sock/v1.18/containers/json?all=1: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?" 


Stdout: 
```

```shell
$ sudo vagrant up                                                                                                                  ⏎
Bringing machine 'default' up with 'docker' provider...
$  sudo vagrant ssh
/usr/share/vagrant/plugins/providers/docker/provider.rb:132:in `[]': no implicit conversion of String into Integer (TypeError)
	from /usr/share/vagrant/plugins/providers/docker/provider.rb:132:in `ssh_info'
	from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:381:in `ssh_info'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/ssh_exec.rb:26:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/providers/docker/action/prepare_ssh.rb:11:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
	from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:196:in `action_raw'
	from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:173:in `block in action'
	from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:157:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:157:in `block in action'
	from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:161:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:161:in `action'
	from /usr/share/vagrant/plugins/commands/ssh/command.rb:59:in `block in execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
	from /usr/lib/ruby/vendor_ruby/vagrant/plugin/v2/command.rb:220:in `each'
	from /usr/lib/ruby/vendor_ruby/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
	from /usr/share/vagrant/plugins/commands/ssh/command.rb:41:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/cli.rb:42:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:258:in `cli'
	from /usr/bin/vagrant:173:in `<main>'
```

I don't know ruby well enough to dive into the Vagrant file code myself.

**Comment by AliasIO** [comment]
Try installing lxc-docker instead. Are you using the latest version of Vagrant?

**Comment by fxfactorial** [comment]
```shell
~/R/Wappalyzer ❯❯❯ vagrant --version
Vagrant 1.6.5
~/R/Wappalyzer ❯❯❯ docker --version
Docker version 1.6.2, build 7c8fca2
```

I don't know what lxc-docker is, looking now.

**Comment by AliasIO** [comment]
I'm also on Docker 1.6.2. If lxc-docker makes no difference, try Vagrant 1.7.2.

**Comment by fxfactorial** [comment]
Just upgraded everything to the latest, lxc, docker and vagrant. Still no dice. Its not a show stopper for me, I'll just try on OS X now.

**Comment by AliasIO** [comment]
It's also possible to run the [shell scripts](https://github.com/AliasIO/Wappalyzer/tree/master/bin) directly. The [Dockerfile](https://github.com/AliasIO/Wappalyzer/blob/master/docker/Dockerfile) shows you what's required, i.e. a couple of environment variables and some packages.

**Comment by fxfactorial** [comment]
@AliasIO Ah, it worked with no problem on OS X, I will follow the dockerfile example for Debian based work. Thanks for your quick replies!
